const idade = 20;// PAI

const exibirIdade = () => {// FILHO
    const idade = 23;// A FUNÇÃO FILHO TEM UMA VARIAVEL COM O MESMO NOME DA VARIAVEL DO PAI
    console.log(idade);// ELE PEGA A VARIAVEL DELE MESMO, SE ELE NÃO TIVER ELE VAI NO PAI
}

const exibirExibirIdade = () => {
    exibirIdade();
    console.log(idade);// MESMO  CHAMANDO A FUNÇÃO DO PAI, ELE NÃO CONSEGUE ACESSAR A VARIAVEL DO PAI
}

exibirIdade();
exibirExibirIdade();

// NO ESCOPO LEXICO A FUNÇÃO ARROW PODE ACESSAR VARIAVEIS FORA DO SEU ESCOPO
// FILHO ACESSA O PAI, MAS O PAI NÃO ACESSA O FILHO


// SE OLHAR QUESTÃO DE CODIGO LIMPO
// ISSO PODE SER CONSIDERADO UM CODE SMELL, POIS PODE GERAR CONFUSÃO
// É ACONSELHAVEL CRIAR NOMES DE VARIAVEIS DIFERENTES PARA NÃO GERAR CONFUSÃO COM 
// AS VARIAVEIS GLOBALS